### ISSUE TITLE
Review 

### ISSUE THREAD

**Issue by alexbalieiro** [cynthiadaubert/desafio-m5#1]
Hola Cynthia, estuve probando tu app, es funcional, cumple el objetivo, en versión mobile funciona sin problemas, pero en versión desktop tiene unos pequeños errores: 

- A los 980px tiene un comportamiento extraño, no se ve el botón de comenzar a jugar y tenes que scrollear para verlo

![Captura de pantalla de 2022-06-23 12-08-13](https://user-images.githubusercontent.com/74037904/175332399-1f44bb79-f208-4945-96cb-d065b9108de8.png)

- El botón de reiniciar puntaje no te lo reinicia 

![Captura de pantalla de 2022-06-23 12-11-47](https://user-images.githubusercontent.com/74037904/175333500-19816c33-8c9d-4d50-8779-381f1a713ae9.png)

- Y el último consejo seria que cuando subas el repo en la pagina de APX sea el link de GitHub y no el de la app directamente porque para hacerte este Issues tuve que buscar tu usuario por acá  😂 

Felicitaciones y a meterle, saludos!

**Comment by cynthiadaubert** [comment]
@alexbal12 Hola Alex! Buenisimo, me pongo a corregir el css y con lo del puntaje me parece que primero mandé la función que redirige al inicio y la parte de borrar los datos quedó de lado, asi que me voy a fijar bien.

Perdón por lo último, me re confundí y quise mandarlo lo mas pronto posible! Gracias por revisarlo!!
